# Generated by Django 5.0.5 on 2026-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
