# Generated by Django 5.0.5 on 2026-05-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_assignmentsubmission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
