# Generated by Django 5.0.5 on 2026-05-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_interactivechallenge_challengeattempt'),
        ('student_portal', '0004_lessonprogress_unlocked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_requests', to='enrollment.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_requests', to='enrollment.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
