# Generated by Django 5.0.5 on 2026-05-18 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('choices_json', models.TextField(help_text='Lista en formato JSON (ej: ["opcion1", "opcion2"])')),
                ('correct_index', models.PositiveIntegerField(help_text='Índice base 0 de la respuesta correcta')),
                ('feedback', models.TextField(help_text='Retroalimentación al responder mal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='enrollment.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='enrollment.student')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='enrollment.interactivechallenge')),
            ],
            options={
                'unique_together': {('student', 'challenge')},
            },
        ),
    ]
